// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD36NIc79Ko2l7Fq3nJruzcgnJAy3ecxYk',
    appId: '1:410923494480:web:6369cadbfd3c2a88aa7555',
    messagingSenderId: '410923494480',
    projectId: 'learning-minh-dart',
    authDomain: 'learning-minh-dart.firebaseapp.com',
    storageBucket: 'learning-minh-dart.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqW1naYl3WKsNe_3fZWatQKE4IxusEzaE',
    appId: '1:410923494480:android:1134a11c4a573520aa7555',
    messagingSenderId: '410923494480',
    projectId: 'learning-minh-dart',
    storageBucket: 'learning-minh-dart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQvfNFA-wkBny1Gnp0LjHnbwec37Vv3EA',
    appId: '1:410923494480:ios:4bd5f87ff88f911caa7555',
    messagingSenderId: '410923494480',
    projectId: 'learning-minh-dart',
    storageBucket: 'learning-minh-dart.appspot.com',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQvfNFA-wkBny1Gnp0LjHnbwec37Vv3EA',
    appId: '1:410923494480:ios:4bd5f87ff88f911caa7555',
    messagingSenderId: '410923494480',
    projectId: 'learning-minh-dart',
    storageBucket: 'learning-minh-dart.appspot.com',
    iosBundleId: 'com.example.learningdart',
  );
}
